<?php

namespace App\Enum;

enum UpdateType: string
{
    case UPDATE_TYPE_INTERNAL_NOTE = 'INTERNAL_NOTE';
    case UPDATE_TYPE_HEARING_OUTCOME = 'HEARING_OUTCOME';
    case UPDATE_TYPE_NEXT_STEP = 'NEXT_STEP';
    case UPDATE_TYPE_CLIENT_MEETING = 'CLIENT_MEETING';
    case UPDATE_TYPE_COURT_FILING = 'COURT_FILING';
    case UPDATE_TYPE_SETTLEMENT = 'SETTLEMENT';
    case UPDATE_TYPE_JUDGMENT = 'JUDGMENT';
}
